enabled: true
hybrid_buffer:
  chunk_strategy: message
  embedding_model: all-MiniLM-L6-v2
  max_size: 5
monitoring:
  enable_stats: true
  log_level: INFO
  performance_tracking: true
performance:
  batch_write_threshold: 5
  enable_async_processing: true
  enable_auto_flush: true
  flush_interval: 60
  flush_strategy: hybrid
  flush_timeout: 30.0
  max_flush_queue_size: 100
  max_flush_workers: 3
query:
  cache_size: 100
  default_order: desc
  default_sort_by: score
  max_size: 15
round_buffer:
  max_size: 5
  max_tokens: 800
  token_model: gpt-4o-mini
token_counter:
  fallback_multiplier: 1.3
  model: gpt-4o-mini
