# @package _global_

# MEMFUSE MAIN CONFIGURATION
# This file serves as the main configuration directory
# Detailed configurations are loaded from subdirectories

# Data directory
data_dir: "data"

# Configuration composition using Hydra defaults
defaults:
  - database: default
  - store: default
  - embedding: default
  - memory: default
  - retrieval: default
  - server: default
  - buffer: default
  - storage: default
  - _self_

# All detailed configurations are loaded from subdirectories
# This keeps the main config file clean and organized
