# @package memory
# MemFuse Memory System Configuration
# Optimized and unified configuration for L0/L1/L2 memory hierarchy

# =============================================================================
# CORE ARCHITECTURE SETTINGS
# =============================================================================

# Processing strategy - controls how layers work together
processing:
  strategy: "parallel"          # parallel | sequential
  enable_fallback: true         # fallback to sequential if parallel fails
  max_concurrent_layers: 3      # maximum layers processing simultaneously

  # Global timeout and retry settings
  timeout:
    per_layer: 30.0            # timeout per layer operation (seconds)
    total_operation: 120.0     # total operation timeout (seconds)

  retry:
    max_attempts: 3            # maximum retry attempts
    base_delay: 1.0           # base delay between retries (seconds)
    max_delay: 10.0           # maximum delay between retries (seconds)
    exponential_backoff: true # use exponential backoff

# =============================================================================
# MEMORY LAYERS CONFIGURATION
# =============================================================================

layers:
  # L0: Episodic Memory - Raw data storage
  l0:
    enabled: true
    priority: 1

    # L0-specific settings
    buffer_size: 1000
    auto_flush_interval: 60    # seconds
    storage_backends: ["vector", "keyword", "sql"]

    # L0 storage tables
    storage:
      message_table: "l0_messages"
      metadata_table: "l0_metadata"

  # L1: Semantic Memory - Fact extraction and processing
  l1:
    enabled: true
    priority: 2

    # L1-specific settings (for future implementation)
    fact_extraction_enabled: true
    llm_model: "grok-3-mini"
    batch_size: 5
    min_confidence_threshold: 0.7

    # L1 storage tables
    storage:
      fact_table: "l1_facts"
      lineage_table: "l1_lineage"
      conflicts_table: "l1_conflicts"

  # L2: Relational Memory - Knowledge graph construction
  l2:
    enabled: true
    priority: 3

    # L2-specific settings
    graph_update_strategy: "incremental"
    entity_resolution_threshold: 0.8
    entity_extraction_enabled: true

    # L2 storage tables
    storage:
      entity_table: "l2_entities"
      relationship_table: "l2_relationships"
      graph_table: "l2_graphs"

# =============================================================================
# STORAGE BACKEND CONFIGURATION
# =============================================================================

storage:
  # Backend-specific connection settings
  vector:
    connection_pool_size: 5
    timeout: 30.0
    batch_size: 100
    store_type: "qdrant"
    enable_transactions: true
    backend: "sqlite"

  keyword:
    connection_pool_size: 3
    timeout: 15.0
    enable_transactions: true
    backend: "sqlite"

  graph:
    connection_pool_size: 3
    timeout: 20.0
    enable_auto_save: true
    store_type: "networkx"
    enable_transactions: true
    backend: "sqlite"

  sql:
    connection_pool_size: 5
    timeout: 30.0
    enable_wal_mode: true
    enable_transactions: true
    backend: "sqlite"

# =============================================================================
# MEMORY SERVICE INTEGRATION
# =============================================================================

# Memory service configuration - controls how MemoryService integrates with layers
memory_service:
  parallel_enabled: true        # Enable L0/L1/L2 parallel processing
  parallel_strategy: "parallel" # Processing strategy
  enable_fallback: true         # Fallback to traditional processing on errors
  log_processing_mode: true     # Log processing decisions
  timeout_per_layer: 30.0       # Timeout per layer (seconds)
  max_retries: 3               # Maximum retry attempts

# =============================================================================
# PERFORMANCE AND MONITORING
# =============================================================================

performance:
  enable_monitoring: true
  enable_caching: true
  cache_size: 1000
  log_interval: 60.0           # performance log interval (seconds)

  # Error handling
  max_error_history: 100
  error_threshold_for_fallback: 0.5  # 50% error rate triggers fallback

# =============================================================================
# ENVIRONMENT-SPECIFIC SETTINGS
# =============================================================================

development:
  enable_debug_logging: false
  enable_performance_profiling: false
  mock_llm_responses: false

production:
  enable_metrics_collection: true
  metrics_export_interval: 300  # seconds
  enable_health_checks: true
  health_check_interval: 60     # seconds
