# @package database
# Database configuration for MemFuse

# Database type: postgres (SQLite fallback removed)
type: "postgres"

# PostgreSQL configuration
postgres:
  host: ${oc.env:POSTGRES_HOST,localhost}
  port: ${oc.env:POSTGRES_PORT,5432}
  database: ${oc.env:POSTGRES_DB,memfuse}
  user: ${oc.env:POSTGRES_USER,postgres}
  password: ${oc.env:POSTGRES_PASSWORD,postgres}
  # HIGH-PERFORMANCE: Optimized for high-throughput streaming scenarios
  # Increased connection pool for better concurrency
  pool_size: 20          # Reasonable base pool for streaming
  max_overflow: 30       # Moderate burst capacity (total 50 connections)
  pool_timeout: 2.0      # Very fast timeout for quick failure detection
  pool_recycle: 600      # 10-minute recycle for better connection reuse
  connection_timeout: 2.0  # Fast connection establishment
  keepalives_idle: 60    # 60-second idle detection for stability
  keepalives_interval: 10  # 10-second keepalive checks
  keepalives_count: 3    # 3 failed checks before disconnect
  
  # Smart connection management settings for high performance
  smart_cleanup:
    enabled: true
    min_idle_connections: 20       # Keep more idle connections for quick access
    max_idle_connections: 30       # Allow more idle connections for high throughput
    idle_timeout_seconds: 120      # Longer timeout for better connection reuse
    cleanup_interval_seconds: 30   # Less frequent cleanup for performance
    burst_threshold: 50            # Higher burst threshold for streaming
    burst_cooldown_seconds: 60     # Longer cooldown for sustained high load


# pgai specific configuration
pgai:
  enabled: true
  vectorizer_worker_enabled: true
  auto_embedding: true
  embedding_model: "all-MiniLM-L6-v2"
  embedding_dimensions: 384
  chunk_size: 1000
  chunk_overlap: 200
  batch_size: 100

  # Immediate trigger configuration
  immediate_trigger: true          # Enable immediate trigger mechanism
  use_polling_fallback: false      # Whether to keep polling as backup

  # Retry mechanism configuration
  max_retries: 3                   # Maximum retry attempts
  retry_interval: 5.0              # Retry interval in seconds
  retry_timeout: 300               # Retry timeout in seconds

  # Worker pool configuration
  worker_count: 3                  # Number of concurrent worker threads
  queue_size: 1000                 # Maximum queue capacity
  batch_processing: false          # Whether to use batch processing

  # Legacy polling configuration (for fallback)
  retry_delay: 5.0                 # Legacy polling interval

  # Monitoring configuration
  enable_metrics: true             # Enable performance monitoring
  log_level: "INFO"               # Log level for embedding operations
