# @package database
# Database configuration for MemFuse

# Database type: postgres (SQLite fallback removed)
type: "postgres"

# PostgreSQL configuration
postgres:
  host: ${oc.env:POSTGRES_HOST,localhost}
  port: ${oc.env:POSTGRES_PORT,5432}
  database: ${oc.env:POSTGRES_DB,memfuse}
  user: ${oc.env:POSTGRES_USER,postgres}
  password: ${oc.env:POSTGRES_PASSWORD,postgres}
  # Global connection pool settings (shared across all stores)
  # Optimized for dual-write mode (BufferService + MemoryService + pgai)
  pool_size: 20          # Minimum connections in pool (optimized for concurrent operations)
  max_overflow: 40       # Additional connections beyond pool_size (increased for dual-write)
  pool_timeout: 60.0     # Timeout for getting connection from pool (increased for complex ops)
  pool_recycle: 7200     # Recycle connections after 2 hours (prevent stale connections)
  connection_timeout: 30.0  # Connection establishment timeout
  keepalives_idle: 600   # TCP keepalive idle time (10 minutes)
  keepalives_interval: 30  # TCP keepalive interval
  keepalives_count: 3    # TCP keepalive count


# pgai specific configuration
pgai:
  enabled: true
  vectorizer_worker_enabled: true
  auto_embedding: true
  embedding_model: "all-MiniLM-L6-v2"
  embedding_dimensions: 384
  chunk_size: 1000
  chunk_overlap: 200
  batch_size: 100

  # Immediate trigger configuration
  immediate_trigger: true          # Enable immediate trigger mechanism
  use_polling_fallback: false      # Whether to keep polling as backup

  # Retry mechanism configuration
  max_retries: 3                   # Maximum retry attempts
  retry_interval: 5.0              # Retry interval in seconds
  retry_timeout: 300               # Retry timeout in seconds

  # Worker pool configuration
  worker_count: 3                  # Number of concurrent worker threads
  queue_size: 1000                 # Maximum queue capacity
  batch_processing: false          # Whether to use batch processing

  # Legacy polling configuration (for fallback)
  retry_delay: 5.0                 # Legacy polling interval

  # Monitoring configuration
  enable_metrics: true             # Enable performance monitoring
  log_level: "INFO"               # Log level for embedding operations
